---
title: "Scope"
format: html
order: 1
---

## Background

Understanding system demand and capacity is essential for operational and strategic healthcare planning. A common approach to demand and capacity planning is spreadsheet modelling and simulating patient flow through the health system. Within each Integrated Care System (ICS) these kinds of model are possible to make, and often already exist. It is much harder to do this at a regional level because the structures and population in each ICS are very different to one another. A tool that is developed to try and capture the intricacies and detail in one ICS is therefore likely to be unrepresentative and open to challenge if used to inform local decision making in another. Additionally, each ICS has developed their own bespoke tools to understand demand and capacity, which already supports local decision making, particularly in the acute setting.

## Project scope

This project aims to understand demand and capacity in a novel way. Using temporal data on demand (e.g., population in older age groups) and capacity (e.g., social care funding) at ICS geography as model inputs, this project aims to predict performance metrics (e.g., No Criteria to Reside remaining in hospital) using modern spatio-temporal modelling techniques. The project would use publicly available data to generate predictions for each ICS. It would also identify which input metrics have the biggest influence on the performance metric being predicted.

## Questions this work can support

Conceptually, the performance metrics should be impacted by the demand and capacity handles. Some of the demand and capacity metrics are ones that can be influenced by policy and investment. This work should be able to identify significant associations between the demand and capacity metrics and the resulting performance. This will help support high-level prioritisation for investment and policy making. For example, if it can be shown there is a strong relationship between social care funding and reducing No Criteria to Reside patients, this can be used to make a strong case for increasing social care funding, if this will be more than offset by the acute cost saving.

## Proposed outputs

The outputs from this work would allow the ICSs to see the relationships between their demand and capacity metrics and performance. The baseline modelling will first produce a ‘do nothing’ performance trajectory, based on current/expected levels of demand and capacity. It will then allow users, through ‘what-if’ scenario analysis, to sensitivity test the models for future years to understand how changes to the input metrics will affect future predictions – thus allowing them to inform more optimal decisions on future spend and resource allocation.