---
title: "Spatio-temporal demand and capacity relationships with performance"
format: docx
---

## Background

Understanding system demand and capacity is essential for operational and strategic planning in the health system. A common approach to demand and capacity modelling is to simulate patient flow through the health system. Within each Integrated Care System this kind of model is possible to make. It is much harder to do this at a regional level because the structures and population in each Integrated Care System within a region are very different to one another. A tool that is developed to try and capture the intricacies and detail is therefore likely to be unrepresentative and open to challenge if attempting to use it to inform local decision making. Additionally, each System has developed their own tools to understand demand and capacity in the short and long term, which supports local decision making.

## Project scope

This project aims to understand demand and capacity in a novel way. Using publicly available data on demand (e.g., population in older age groups) and capacity (e.g., Social Care funding) at Integrated Care Board (ICB) geography as model inputs, this project aims to predict publicly available performance data (e.g., No Criteria to Reside remaining in hospital) using modern modelling techniques. The project would use data available nationally to generate predictions for each ICB. It would also identify which input metrics have the biggest influence on the performance metric being predicted.

## Questions this work can support

Conceptually, the performance metrics should be impacted by the demand and capacity metrics. Some of the demand and capacity metrics are ones that can be influenced by policy and investment. This work should be able to identify significant associations between the demand and capacity metrics and the resulting performance. This will help support prioritisation for investment and policy making.  For example, if it can be shown there is a strong relationship between social care funding and reducing No Criteria to Reside patients, this can be used to make a strong case for increasing social care funding.

## Proposed outputs

The outputs from this work would allow users to see the relationships between the demand and capacity metrics and the performance metrics. It will also allow users to sensitivity test the models for future years to understand how changes to the input metrics will affect future predictions - allowing them to inform decisions on future spend. 
